#!/bin/bash
##nano /usr/local/bin/blacklist_RPiList_slave && chmod +x /usr/local/bin/blacklist_RPiList_slave

downloadDIR=/tmp/pihole_lists
piholeDIR=/etc/pihole
blocklists="https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten.md"

# Prüft ob das Downloadverzeichnis existiert, wenn NICHT wird das Verzeichnis erstellt.
if [ ! -d "$downloadDIR" ]; then
    sudo mkdir -p "$downloadDIR"
fi

# In Downloadverzeichnis wechseln.
cd "$downloadDIR" || exit

# Ladet die Blocklisten von "sempervideo" herunter und schreibt sie in die Datei "adlists.down". Alte Einträge werden überschrieben.
curl $blocklists | grep "\*" | cut -f2 -d' ' | sort -u > adlists.down


# Prüft ob die Datei "adlists.down" bereits existiert, wenn JA wird sie gelöscht.
if [ -f "adlists.list" ]; then
    sudo rm adlists.list
fi

# Die gewünschten Blocklisten, die aus der Datei "adlists.down" übernommen werden sollen, hinzufügen.
link=("StevenBlack" "malwaredomains.com" "s3.amazonaws.com" "adaway.org" "ChanBlocker"
      "hosts-blocklists" "v.firebog.net" "PiHoleBlocklist" "W10TelemetryBlocklist" "RPiList")

# Links der gewünschten Blocklisten werden in der Datei "adlists.list" gespeichern.
for url in "${link[@]}"; do
    grep "$url" adlists.down >> adlists.list
done

# Auskommentieren -> hier z.B. die "pornblock" Listen 1-4 von RPiList.
#sed -i '/pornblock.*/ s/^#*/#/' adlists.list
# oder Löschen
#sed -i '/pornblock.*/ D' adlists.list

# Verschiebt die neue Blocklistedatei ins Pi-hole Verzeichnis.
sudo mv adlists.list "$piholeDIR"/adlists.list



# Dateien die heruntergeladen werden sollen.
scripturls=("https://raw.githubusercontent.com/Deagol-03/pihole/master/regex.list"
            "https://raw.githubusercontent.com/Deagol-03/pihole/master/blacklist.txt"
            "https://raw.githubusercontent.com/Deagol-03/pihole/master/whitelist.txt")

# Dateien herunterladen und ins Pi-hole Verzeichnis verschieben.
for url in "${scripturls[@]}"; do
    # Script downloaden.
    sudo wget -N "$url"
    # Dateiname aus URL mittels RegEx extrahieren.
    file=$(echo "$url" | sed 's/.*\///')
    # Datei(en) verschieben ins Pi-hole Verzeichnis.
    sudo mv "$file" "$piholeDIR"/"$file"
done

# Aktualisierte Listen beim Pi-hole neu einlesen.
pihole -g
